[versions]
kotlin = "2.1.21"
exposed = "0.60.0"
ksp = "2.1.21-2.0.1"


[plugins]
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
vanniktech-mavenPublish = { id = "com.vanniktech.maven.publish", version = "0.29.0" }
serial = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

[libraries]
ksp-api = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp" }
kotlinpoet = { module = "com.squareup:kotlinpoet", version = "2.2.0" }
kotlinpoet-interop = { module = "com.squareup:kotlinpoet-ksp", version = "2.2.0" }
exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed" }
exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposed" }
exposed-dao = { module = "org.jetbrains.exposed:exposed-dao", version.ref = "exposed" }
exposed-kotlin-datetime = { module = "org.jetbrains.exposed:exposed-kotlin-datetime", version.ref = "exposed" }
exposed-java-time = { module = "org.jetbrains.exposed:exposed-java-time", version.ref = "exposed" }
exposed-json = { module = "org.jetbrains.exposed:exposed-json", version.ref = "exposed" }
datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version = "0.6.2" }

serial = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version = "1.6.1" }
